# Generated by Django 4.2.30 on 2026-05-15 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(default='CLIENTE', max_length=50)),
                ('pontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regra', models.CharField(default='Padrao', max_length=100)),
                ('pontos_por_real', models.IntegerField(default=1)),
                ('resgate_clientes', models.IntegerField(default=30)),
                ('resgate_indicantes', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('perfil', models.CharField(max_length=50)),
                ('comissao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendedor', models.CharField(max_length=100)),
                ('cliente', models.CharField(default='CONSUMIDOR PADRAO', max_length=200)),
                ('indicante', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cupom_texto', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VENDA', 'Venda Finalizada'), ('ORCAMENTO', 'Orçamento')], default='VENDA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cod_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('unidade', models.CharField(default='UN', max_length=20)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.familia')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca')),
            ],
        ),
    ]
