# Generated by Django 6.0.5 on 2026-05-25 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='cor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relacaoembalagenstintometrico',
            name='produto_cod_interno',
            field=models.ForeignKey(db_column='produto_cod_interno', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.produtos', to_field='cod_interno'),
        ),
    ]
