# Generated by Django 6.0.5 on 2026-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('CLIENTE', 'Cliente Regular'), ('PINTOR', 'Pintor / Indicante')], max_length=20, unique=True)),
                ('pontos_por_real', models.IntegerField(default=1)),
                ('pontos_necessarios_resgate', models.IntegerField(default=30)),
                ('valor_resgate_reais', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Configuracoes',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='status',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='unidade',
            field=models.CharField(default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(default='Colaborador', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='indicante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
