# Generated by Django 6.0.5 on 2026-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_configuracaopontos_delete_configuracoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='status',
            field=models.CharField(default='ATIVO', max_length=20),
        ),
    ]
