# Generated by Django 4.2.30 on 2026-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_produtos_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='es_base_tintometrica',
            field=models.BooleanField(default=False),
        ),
    ]
