# Generated by Django 4.2.30 on 2026-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_clientes_pontos_clientes_bairro_clientes_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(default='JB TINTAS', max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('inscricao_estadual', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('codigo_ibge', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='codigo_ibge',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='cfop',
            field=models.CharField(default='5102', max_length=10),
        ),
        migrations.AddField(
            model_name='produtos',
            name='cst_csosn',
            field=models.CharField(default='0102', max_length=10),
        ),
        migrations.AddField(
            model_name='produtos',
            name='ncm',
            field=models.CharField(default='32091010', max_length=15),
        ),
        migrations.AddField(
            model_name='vendas',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/pdfs/'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='arquivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/xmls/'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='motivo_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='numero_nota',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='status_fiscal',
            field=models.CharField(default='SEM_NOTA', max_length=50),
        ),
    ]
