# Generated by Django 6.0.5 on 2026-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_produtos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='endereco',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
