# Generated by Django 4.2.30 on 2026-05-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_configuracaoemissor_clientes_codigo_ibge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemissor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produtos',
            name='cest',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='origem',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='produtos',
            name='unidade_tributavel',
            field=models.CharField(default='UN', max_length=10),
        ),
    ]
