# Generated by Django 4.2.30 on 2026-06-03 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_configuracaoemissor_email_produtos_aliquota_icms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(choices=[('SAIDA', 'Saída'), ('ENTRADA', 'Entrada')], default='SAIDA', max_length=10)),
                ('natureza_operacao', models.CharField(default='Venda de mercadoria', max_length=100)),
                ('cfop', models.CharField(default='5102', max_length=5)),
                ('consumidor_final', models.CharField(choices=[('1', '1 - Sim'), ('0', '0 - Não')], default='1', max_length=1)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('indicador_presenca', models.CharField(choices=[('0', '0 - Não se aplica'), ('1', '1 - Operação presencial'), ('2', '2 - Operação não presencial, pela Internet'), ('3', '3 - Operação não presencial, Teleatendimento'), ('4', '4 - NFC-e em operação com entrega a domicílio'), ('5', '5 - Operação presencial, fora do estabelecimento')], default='1', max_length=1)),
                ('informacoes_complementares', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.clientes')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_nf', to='inventario.vendas')),
            ],
            options={
                'db_table': 'dados_nf',
            },
        ),
    ]
