# Generated by Django 4.2.30 on 2026-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_dadosnf'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='modelo_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
