# Generated by Django 4.2.30 on 2026-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_vendas_modelo_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosnf',
            name='cofins_cst',
            field=models.CharField(default='07', max_length=5),
        ),
        migrations.AddField(
            model_name='dadosnf',
            name='pis_cst',
            field=models.CharField(default='07', max_length=5),
        ),
    ]
