# Generated by Django 4.2.30 on 2026-06-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_dadosnf_cofins_cst_dadosnf_pis_cst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='cfop',
        ),
    ]
