# Generated by Django 4.2.30 on 2026-06-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0008_remove_produtos_cfop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoEletronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('entrada_1', models.TimeField(blank=True, null=True)),
                ('saida_1', models.TimeField(blank=True, null=True)),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('saida_2', models.TimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ponto Eletrônico',
                'verbose_name_plural': 'Pontos Eletrônicos',
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
