# Generated by Django 4.2.30 on 2026-06-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_pontoeletronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='H_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='H_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='T_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontoeletronico',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.usuarios'),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='inventario_usuarios',
        ),
    ]
