# Generated by Django 4.2.30 on 2026-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_usuarios_h_entrada_usuarios_h_saida_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pontoeletronico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pontoeletronico',
            name='colaborador_login',
            field=models.CharField(default='sistema', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pontoeletronico',
            unique_together={('colaborador_login', 'data')},
        ),
        migrations.RemoveField(
            model_name='pontoeletronico',
            name='colaborador',
        ),
    ]
