# Generated by Django 4.2.30 on 2026-06-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_pontoeletronico_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='H_entrada',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='H_saida',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='T_almoco',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='escala_semanal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
