# Generated by Django 4.2.30 on 2026-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_usuarios_h_entrada_remove_usuarios_h_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(default='Vendedor', max_length=50),
        ),
    ]
