# Generated by Django 4.2.30 on 2026-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_usuarios_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoemissor',
            options={'verbose_name': 'Configuração do Emissor', 'verbose_name_plural': 'Configurações do Emissor'},
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='ambiente_gnf',
            field=models.CharField(choices=[('producao', 'Produção'), ('homologacao', 'Homologação (Testes)')], default='homologacao', max_length=20, verbose_name='Ambiente de Emissão'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='token_gnf',
            field=models.CharField(blank=True, help_text='Insira o Token de Acesso gerado no painel da API.', max_length=255, null=True, verbose_name='Token Gerando Nota Fácil'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='id_transacao_api',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transação GNF'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='link_pdf',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link DANFE Online'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='link_xml',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link XML Online'),
        ),
    ]
