# Generated by Django 4.2.30 on 2026-08-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_configuracaoemissor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='aviso_estoque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='cod_forn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
