# Generated by Django 4.2.30 on 2026-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_produtos_aviso_estoque_produtos_cod_forn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
