# Generated by Django 4.2.30 on 2026-08-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='modulo_pontuacao_cliente_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativar Pontuação para Clientes'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='modulo_pontuacao_pintor_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativar Pontuação para Pintores/Indicantes'),
        ),
    ]
