# Generated by Django 4.2.30 on 2026-08-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_configuracaosistema_modulo_pontuacao_cliente_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RupturaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_perdida', models.IntegerField(default=1)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rupturas', to='inventario.produtos')),
            ],
        ),
    ]
