# Generated by Django 4.2.30 on 2026-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_rupturaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data_previsao_chegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='qtd_em_transito',
            field=models.IntegerField(default=0),
        ),
    ]
