# Generated by Django 4.2.30 on 2026-08-07 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_produtos_data_previsao_chegada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(blank=True, help_text='Um texto curto para aparecer no painel', max_length=300, null=True)),
                ('conteudo', models.TextField(help_text='O texto completo da atualização')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
    ]
