# Generated by Django 4.2.30 on 2026-08-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto (Em Contagem)'), ('FINALIZADO', 'Finalizado (Auditado)')], default='ABERTO', max_length=20)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_criados', to='inventario.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_sistema', models.IntegerField(default=0)),
                ('saldo_fisico', models.IntegerField(default=0)),
                ('data_contagem', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.produtos')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_contados', to='inventario.inventariosessao')),
            ],
        ),
    ]
