# Generated by Django 4.2.30 on 2026-08-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_inventariosessao_inventarioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventariosessao',
            name='sessao_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.sessaoestoque'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='sessao_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='inventario.sessaoestoque'),
        ),
    ]
