# Generated by Django 4.2.30 on 2026-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_sessaoestoque_inventariosessao_sessao_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='cst_csosn',
            field=models.CharField(default='0102', max_length=50),
        ),
    ]
