# Generated by Django 4.2.30 on 2026-09-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_produtos_cst_csosn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='cliente_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cliente', to='inventario.clientes'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='indicante_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes_pintor', to='inventario.clientes'),
        ),
    ]
