# Generated by Django 4.2.30 on 2026-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_vendas_cliente_link_vendas_indicante_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
