# Generated by Django 4.2.30 on 2026-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_clientes_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
