# Generated by Django 4.2.30 on 2026-09-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_vendas_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariosessao',
            name='sessao_estoque',
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='contado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventariosessao',
            name='filtro_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.familia'),
        ),
        migrations.AddField(
            model_name='inventariosessao',
            name='filtro_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca'),
        ),
        migrations.AddField(
            model_name='inventariosessao',
            name='filtro_unidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
