# Generated by Django 4.2.30 on 2026-09-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_remove_inventariosessao_sessao_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosessao',
            name='valor_perda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariosessao',
            name='valor_sobra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimento', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_novo', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.usuarios')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.produtos')),
            ],
        ),
    ]
