# Generated by Django 4.2.30 on 2026-09-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_inventariosessao_valor_perda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: JB Tintas Tatuapé', max_length=100, unique=True)),
                ('codigo_ibge', models.CharField(help_text='Ex: 3550308', max_length=10)),
                ('ultima_busca_feriados', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(choices=[('Vendedor', 'Vendedor'), ('Gerente', 'Gerente'), ('Supervisor', 'Supervisor'), ('DEV', 'Desenvolvedor')], default='Vendedor', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='inventario.lojafilial'),
        ),
        migrations.CreateModel(
            name='FeriadoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='inventario.lojafilial')),
            ],
            options={
                'unique_together': {('loja', 'data')},
            },
        ),
    ]
