# Generated by Django 4.2.30 on 2026-09-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_lojafilial_alter_usuarios_perfil_usuarios_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.usuarios'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='kardex',
            table='inventario_kardex',
        ),
        migrations.CreateModel(
            name='AlertaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual (Cadastro)'), ('AUTOMATICA', 'Automática (XML NFe)')], max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_preco', to='inventario.produtos')),
            ],
        ),
    ]
