# Generated by Django 4.2.30 on 2026-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_alter_kardex_custo_unitario_alter_kardex_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ind_ie',
            field=models.CharField(choices=[('1', '1 - Contribuinte ICMS (Informar IE)'), ('2', '2 - Contribuinte Isento de Inscrição'), ('9', '9 - Não Contribuinte (Pessoa Física ou Sem IE)')], default='9', max_length=1, verbose_name='Indicador de Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='cfop_padrao_externo',
            field=models.CharField(default='6102', max_length=4, verbose_name='CFOP Padrão (Fora do Estado)'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='cfop_padrao_interno',
            field=models.CharField(default='5102', max_length=4, verbose_name='CFOP Padrão (Dentro do Estado)'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='crt',
            field=models.CharField(choices=[('1', '1 - Simples Nacional'), ('2', '2 - Simples Nacional - Excesso de Sublimite'), ('3', '3 - Regime Normal (Lucro Presumido/Real)'), ('4', '4 - Simples Nacional (MEI)')], default='1', max_length=1, verbose_name='Código de Regime Tributário'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='csc_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID do CSC (Token Sefaz)'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='csc_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código CSC (Token Sefaz)'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='csosn_padrao',
            field=models.CharField(default='102', help_text='Ex: 102 (Tributada pelo Simples Nacional)', max_length=4, verbose_name='CSOSN Padrão'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='natureza_operacao_padrao',
            field=models.CharField(default='VENDA DE MERCADORIA', max_length=100, verbose_name='Natureza da Operação'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='cfop_especifico',
            field=models.CharField(blank=True, help_text='Ex: 5102, 5405. Se vazio, usa o da Loja.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='codigo_ibge',
            field=models.CharField(blank=True, help_text='Código de 7 dígitos do Município', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoemissor',
            name='ambiente_gnf',
            field=models.CharField(choices=[('producao', 'Produção (Com Valor Fiscal)'), ('homologacao', 'Homologação (Testes)')], default='homologacao', max_length=20, verbose_name='Ambiente de Emissão'),
        ),
        migrations.AlterField(
            model_name='configuracaoemissor',
            name='token_gnf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Gerando Nota Fácil (NotaaS)'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cest',
            field=models.CharField(blank=True, help_text='Exigido se houver Retenção ICMS (ST)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cst_csosn',
            field=models.CharField(blank=True, help_text='Ex: 102, 500. Se vazio, usa o da Loja.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ncm',
            field=models.CharField(default='32091010', help_text='Nomenclatura Comum do Mercosul', max_length=15),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='origem',
            field=models.CharField(default='0', help_text='0 - Nacional, 1 - Estrangeira Importação Direta, etc.', max_length=1),
        ),
    ]
