# Generated by Django 4.2.30 on 2026-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_clientes_ind_ie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoemissor',
            name='ambiente_gnf',
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='ambiente_nfce',
            field=models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=20, verbose_name='Ambiente NFC-e (Modelo 65)'),
        ),
        migrations.AddField(
            model_name='configuracaoemissor',
            name='ambiente_nfe',
            field=models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=20, verbose_name='Ambiente NF-e (Modelo 55)'),
        ),
    ]
