# Generated by Django 4.2.30 on 2026-09-22 17:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_remove_configuracaoemissor_ambiente_gnf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, null=True)),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.AlterField(
            model_name='configuracaoemissor',
            name='csc_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, null=True, verbose_name='ID do CSC (Token Sefaz)')),
        ),
        migrations.AlterField(
            model_name='configuracaoemissor',
            name='csc_token',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True, verbose_name='Código CSC (Token Sefaz)')),
        ),
        migrations.AlterField(
            model_name='configuracaoemissor',
            name='token_gnf',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Gerando Nota Fácil (NotaaS)')),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
